version: "3.3"

networks:
  demo:
    driver: bridge

services:
  app:
    depends_on:
      - db
    build: ./
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    ports:
      - 9652:80
    stdin_open: true
    tty: true
    networks:
      - demo
  db:
    image: mysql:5.7.33
    restart: always
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ssm
      - MYSQL_USER=ssm
      - MYSQL_PASSWORD=development
      - MYSQL_ROOT_PASSWORD=@p1ss1g2m
    networks:
      - demo
